import { iPropertyBase } from "./Ipropertybase";
import { photo } from './photo';
export class property implements iPropertyBase{
  id!: number | null;
  name!: string | null;
  price!: number | null;
  sellRent!: number | null;
  furnishingType!: number | null;
  propertyType!: number | null;
  type!: string | null;
  bhk!: number | null;
  builtArea!: number | null;
  AOP?:string;
  city!: string;
  image?: string;
  propertyTypeId!: number|null;
  furnishingTypeId!: number|null;
  carpetArea?: number|null;
  address!: string|null;
  address2?: string|null;
  CityId!: number|null;
  floorNo?: string|null;
  totalFloors?: string|null;
  readyToMove!: boolean|null;
  age?: string|null;
  mainEntrance?: string|null;
  security?: number|null;
  gated?: boolean|null;
  maintenance?: number|null;
  PossessionOn?: string|null;
  estPossessionOn?: string | null;
  photo?: string|null;
  description?: string|null;
  postedon?:string|null;
  postedby?:string|null;
  EstPossessionOn?:Date;
  photos?:photo[];
}
